# Generated by Django 5.0.6 on 2024-06-22 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoListApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='todo',
            table='TodoListApp_db',
        ),
    ]
