# Generated by Django 5.0.6 on 2024-12-05 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_suggest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('produce', models.TextField()),
                ('keywords', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='MindMap',
        ),
    ]
