# Generated by Django 5.0.6 on 2024-05-29 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendarApp', '0002_remove_event_title_event_name_alter_event_end_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='event',
            table='calendarApp_db',
        ),
    ]
