# Generated by Django 5.0.6 on 2024-05-31 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendarApp', '0003_alter_event_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='name',
            new_name='title',
        ),
    ]
