# Generated by Django 5.0.6 on 2024-06-12 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountbookApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='category',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='title',
        ),
        migrations.AddField(
            model_name='transaction',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
