# Generated by Django 5.0.6 on 2024-06-12 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountbookApp', '0002_remove_transaction_category_remove_transaction_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_type',
        ),
        migrations.AddField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], default='income', max_length=10),
        ),
    ]
